src/index_fr.md

Hi @biilmann,
In order to spread the JAM to french speaking people, I took the liberty to translate your content.
If it's OK with you, I could also publish it elsewhere, if you don't want to host translations.

French translation

---

src/br/index.md

If it's useful for you, here goes a Brazilian portuguese translation ;-)

Brazilian Portuguese translation

---

site/data/resources.yaml

Go static: 5 reasons to try JAMstack on your next project
https://builtvisible.com/go-static-try-jamstack/

Added new JAMstack article to resources page

---

site/data/resources.yaml

docs(resources/articles): add JAMstack tutorial

---

site/data/examples.yaml

move to Gitea source control, add Pygments, add SES/DKIM, add [SpeedTracker](https://speedtracker.org), remove libs, update description

docs(examples): update hack cabin tools

---

site/data/examples.yaml

This also fix a few capitalizations.
PS: Thanks for creating this site, I totally rally behind these principles!

docs(examples): It's Sass, not SASS

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE

Realized that we were missing these

make contributor friendly

---

site/layouts/index.html

How on Earth did we never notice this? Hah

Fix JAMstack capitalization in first heading!

---

site/layouts/pages/resources.html

load videos on window.onload (resources.html)

---

site/data/resources.yaml

I wrote this one a few months ago and just realized I never added it here. Let me know if anyone has any questions!

Added article Static Websites + JAMstack = <3 to resources.

---

site/data/community.yaml

Related to https://github.com/jamstack/jamstack.org/pull/112

fix: Add Jamstack Portland

---

site/data/definitions.yaml

Sorry if this is too nitpicky. I was just reading through the homepage and thought it would be better to encourage HTTPS everywhere. Thanks for all your work!

Changed HTTP to HTTPS

---

src/css/imports/header.css

Let's get back the way it used to be before #128

style: remove margin added for the former banner

---

site/data/community.yaml

Update the community page with the new JAMstack_Seattle meetup: https://www.meetup.com/jamstack-seattle/

Update JAMstack Seattle with community link

---

site/data/definitions.yaml
site/layouts/index.html
src/css/imports/hero.css
src/css/imports/jam-breakdown.css

A small step on the way to refreshing this site with some clarified messaging.

Minor wording updates

---

site/data/community.yaml

Hey Friends,
I would like to change the JAMstack Berlin meetup link 
cc @philhawksworth

Change Jamstack Berlin Link

---

site/layouts/partials/header.html
src/css/imports/header.css

Fix diversity menu active link style

---

site/data/resources.yaml
site/layouts/page/resources.html

I added a new article to the resource page
https://www.bolajiayodeji.com/introducing-jamstack-the-modern-web-architecture/

added a new resource

---

site/data/examples.yaml

Removed example to site with crytpo mining

---

site/data/resources.yaml

Title: What is the Jamstack and how do I get started?
Link: https://www.freecodecamp.org/news/what-is-the-jamstack-and-how-do-i-host-my-website-on-it/
Thought this article I wrote could be useful :) seemed to go over well from those who took a read.

[article] What is the JAMstack and how do I get started? freecodecamp.org

---

site/data/examples.yaml

Fix tag according to [Kentico Cloud -> Kentico Kontent rebranding](https://www.kentico.com/blog/moving-to-content-as-a-service-with-kentico-kontent)

Fix tag according to the Kontent re-branding

---

site/data/resources.yaml

added "What is JAMstack and How Does it Work?" to articles section.

added "What is JAMstack and How Does it Work?"

---

site/layouts/index.html
site/layouts/partials/promo.html

We'll settle on the unified adopted spelling for suggested broader use soon.

Just for consistency for now

---

CONTRIBUTING.md
site/data/examples.yaml
site/data/resources.yaml
site/layouts/page/examples.html
src/css/imports/header.css

Following [the discussion](#279) about how write the word "Jamstack" consistently, updating any remaining references to ensure we only use "Jamstack" in the copy on this site.

Use "Jamstack" consistently

---

site/layouts/partials/promo.html

New announcement bar content for https://github.com/netlify/marketing/issues/1194 (generated via shell script 😅)

Announcement Bar (jamstack.org)

---

.eleventy.js
src/site/_includes/components/cms-card.njk
src/site/_includes/components/generator-card.njk
src/site/_includes/layouts/base.njk
src/site/_includes/layouts/glossary.njk
src/site/best-practices.njk
src/site/code-of-conduct.njk
src/site/community.njk
src/site/examples.njk
src/site/generators.njk
src/site/glossary-pages.njk
src/site/glossary.njk
src/site/headless-cms.njk
src/site/logos.njk
src/site/resources/index.njk
src/site/styleguide.njk
src/site/what-is-jamstack.njk
src/site/why-jamstack.njk

work-in-progress pr/branch for Scott to add metadata and optimize markup throughout, prior to launch

SEO and markup edits

---

src/site/_getting-started.njk
src/site/glossary-pages.njk
src/site/resources/a-jamstack-ready-cms.md
src/site/resources/articles.njk
src/site/resources/bringing-jamstack-to-the-enterprise.md
src/site/resources/dynamic-product-management-in-a-static-e-commerce-workflow.md
src/site/resources/easy-isomorphic-rendering-on-the-jamstack.md
src/site/resources/freecodecamp-full-jamstack-course.md
src/site/resources/go-static-5-reasons-to-try-jamstack-on-your-next-project.md
src/site/resources/going-jamstack-with-netlify-and-nuxt.md
src/site/resources/how-to-build-a-jamstack-website.md
src/site/resources/index.njk
src/site/resources/introducing-jamstack-the-modern-web-architecture.md
src/site/resources/isomorphic-rendering-on-the-jamstack.md
src/site/resources/jamstack-modern-web-architecture-in-digestible-terms.md
src/site/resources/jamstack-training-free-video-courses-on-jamstack-technologies.md
src/site/resources/new-to-jamstack-everything-you-need-to-know-to-get-started.md
src/site/resources/rise-of-the-jamstack.md
src/site/resources/static-websites-jamstack-less3.md
src/site/resources/the-new-front-end-stack-javascript-apis-and-markup.md
src/site/resources/what-is-jamstack-and-how-does-it-work.md
src/site/resources/what-is-jamstack-and-why-you-should-try-it.md
src/site/resources/what-is-the-jamstack-and-how-do-i-get-started.md
src/site/resources/zero-to-http2-with-aws-and-hugo.md
src/site/sitemap.njk

Adds a sitemap and introduce new self explanatory Front Matter fields:
```
excludeFromSitemap
lastmod
changefreq
priority
```
https://deploy-preview-362--jamstack-site.netlify.app/sitemap.xml

Add sitemap

---

src/site/headless-cms/apostrophecms.md

Adds ApostropheCMS to the set of headless CMSs.

Adds ApostropheCMS to list of headless CMSs

---

src/site/what-is-jamstack.njk

Fix: spelling error

---

README.md

I updated this to what I think is the correct directory? I was not sure, but what was there before I don't think is correct.

Updated image link

---

src/site/resources/freecodecamp-full-jamstack-course.md

Fix date on Learn Jamstack video

---

src/site/generators/verless.md

This PR add verless/verless. Thanks in advance!

Add verless

---

src/site/generators/cleaver.md
src/site/generators/statamic.md

* statamic - Fix broken link to homepage
* statamic - Reformat repo metadata
* cleaver - add slash to homepage in attempt to resolve rendering issue
* cleaver - reorder metadata in attempt to resolve rendering issue

Fix Broken Links

---

src/site/what-is-jamstack.njk

Fixed the redirecting not working issue.
fix #422

fix : API Economy redirection not working

---

src/site/generators/beautiful-jekyll.md
src/site/generators/finch.md
src/site/generators/hexo.md
src/site/generators/jungle.md
src/site/generators/mkws.md
src/site/generators/routify.md
src/site/generators/soupault.md
src/site/headless-cms/crystallize.md
src/site/headless-cms/frontaid.md
src/site/headless-cms/sensenet.md

https://github.com/netlify/headlesscms.org/pull/370
https://github.com/netlify/headlesscms.org/pull/356
https://github.com/netlify/headlesscms.org/pull/350
https://github.com/netlify/headlesscms.org/pull/335
https://github.com/netlify/staticgen/pull/900
https://github.com/netlify/staticgen/pull/898
https://github.com/netlify/staticgen/pull/897
https://github.com/netlify/staticgen/pull/896
https://github.com/netlify/staticgen/pull/886
https://github.com/netlify/staticgen/pull/869
https://github.com/netlify/staticgen/pull/866
https://github.com/netlify/staticgen/pull/897
https://github.com/netlify/staticgen/pull/886

Updates from remaining PRs of staticgen / headlesscms

---

src/site/what-is-jamstack.njk

Fix typo in what-is-jamstack.njk

---

src/site/headless-cms/acoustic-content.md

As per https://acoustic.com/products/content/

Replace "IBM" with "Acoustic"

---

src/site/community.njk

Use jamstack.org domain for email

---

src/site/generators/nuxt.md

Fixed a typo

---

src/site/what-is-jamstack.njk

pretty sure 'for' was meant to be 'far' on line 37

tiny typo (I think) in what-is-jamstack.njk

---

src/site/generators.njk

Filter text/background color

---

src/site/_data/examples/ahaquiz.yaml

Typo on examples page

---

src/site/generators/lume.md

Lume is a static site generator for Deno.

Add Lume as static site generator

---

src/site/generators/blogcpp.md

Add BlogC++

---

src/site/headless-cms/apostrophecms.md

Fixes two incorrect links and one broken link. Thanks!

Fixes links for Apostrophe profile

---

src/site/generators/soupault.md

Make some minor adjustments in the description, too.

Update the soupault site URL.

---

src/site/headless-cms/payload-cms.md

Add [Payload CMS](https://payloadcms.com) to list of Headless CMSs

Add Payload CMS to list of Headless CMSs

---

src/site/generators/log4brains.md

The install procedure of Log4brains has changed since [this PR](https://github.com/jamstack/jamstack.org/pull/482) was merged.

Fix Log4brains install procedure

---

src/site/_data/glossary.yaml

Expanding the glossary:
https://ph-glossary-updates--jamstack-site.netlify.app/glossary/immutable/
https://ph-glossary-updates--jamstack-site.netlify.app/glossary/atomic/
https://ph-glossary-updates--jamstack-site.netlify.app/glossary/serverless/

adding: serverless, atomic, immutable

---

src/site/why-jamstack.njk

Fixed typo

---

src/site/generators/next.md

Updates the template repo to one with more modern Next.js usage samples.
cc @cassidoo since it's your repo. :)

Update Next.js template repo

---

src/site/tv.njk

Links the Algolia logo on https://deploy-preview-539--jamstack-site.netlify.app/tv/

Adds Algolia logo link on TV page (by request)

---

src/site/generators/saga.md

Added only the second generator written in Swift.

Added Saga

---

src/site/headless-cms/ghost.md

This PR fixes a typo on the Ghost page.

Fix typo on Ghost page.

---

src/site/generators/nuxt.md

Fixed typo in nuxt.md

---

src/site/generators/squido.md

Adding [squido](https://squido.org) to the website generators section.

Adding `squido` to site generators

---

src/site/_data/community.yaml

https://github.com/jamstack/jamstack.org/issues/547

Fixes #547 (Florence is not in the USA)

---

src/site/generators/ema.md

This is my static site generator written for Haskell programmers in particular, and inspired in part by SvelteKit:
https://ema.srid.ca/

Add ema static site generator (Haskell)

---

src/css/tailwind.css
src/site/_data/announcementbar.json
src/site/_includes/components/zinger-cta.njk
src/site/css/hubspot-form.css
src/site/survey-closed.njk
src/site/survey-confirmation.njk
src/site/survey-thanks.njk

Add Jamstack Survey confirmation pages
https://deploy-preview-597--jamstack-site.netlify.app/survey-confirmation/
https://deploy-preview-597--jamstack-site.netlify.app/survey-thanks/
https://deploy-preview-597--jamstack-site.netlify.app/survey-closed/

Add Survey confirmation pages

---

netlify.toml
src/site/_data/announcementbar.json

https://deploy-preview-598--jamstack-site.netlify.app/survey should redirect to Survey Monkey

Add survey redirect

---

src/site/generators/squido.md

Fixed startertemplaterepo pointing to a dead repository.

Updated squido startertemplaterepo link

---

src/site/headless-cms/cloudcannon.md

Updating CloudCannon description to include support for static site generator Hugo.

Update CloudCannon Description

---

netlify.toml

#605
https://deploy-preview-606--jamstack-site.netlify.app/conf/cfp
Before: https://wheregoes.com/trace/20214883598/
After: https://wheregoes.com/trace/20214883590/

Remove one CFP redirect in the chain.

---

src/site/generators/wb.md

Hello,
This adds https://mtod.org/wb metadata to static generators index.
Thank you.

Add Writer's Block to static generators

---

src/site/community.njk

Updating the process for starting a meetup

link to handbook instead of email

---

src/site/_data/community.yaml

Adding Stuttgart to the `/community` as per #611

welcoming Stuttgart

---

src/site/generators/nuxt.md

Link to a different starter template to fix #538

Replace starter template

---

.github/workflows/scheduled-build.yml

Fixes https://github.com/jamstack/jamstack.org/issues/562
Primarily this serves as a mechanism to update the star counts and other GitHub metadata for the listing pages.

Adds GitHub action to do daily build

---

src/site/generators/coppersmith.md
src/site/generators/hydrogen.md
src/site/generators/intu-dev.md
src/site/generators/nift.md
src/site/generators/pft.md
src/site/generators/templer.md
src/site/headless-cms/hashbrown.md

This PR fixes dead links for some project homepages.

Fix project homepage dead links.

---

src/site/headless-cms/cloudcannon.md

Additional updates include updating our workflow and community resource link.

Update CloudCannon, to include 11ty

---

netlify.toml

Remove the old survey redirect

Fix /survey redirect

---

src/site/headless-cms/tinacms.md

Updating TinaCMS to reflect where Tina stands in 2021/2022:
- Updated frameworks
- Updated Gif
- Updated Discord
- Updated Links

Updating TinaCMS to be correct

---

netlify.toml
src/site/_data/announcementbar.json
src/site/_includes/header.njk

New link to sidebar links for new route `/women-of-jamstack`
This comes alongside an additional redirect to the new website and a new banner callout announcing the site.

Adding Women of Jamstack to links 

---

package.json

- removed live-server
- upgraded to v1 of 11ty 
- fixed the scripts now that live-server is gone

Remove live-server / upgrade 11ty 

---

src/site/generators/curvenote.md

Add Curvenote CLI,  a node.js based site generator

Add Curvenote

---

src/site/generators/fresh.md

Addin Fresh the new Deno framework
https://fresh.deno.dev/

fresh-deno

---

src/site/generators/fossfolio.md

Add details about [**fossfolio**](https://gihub.com/anuran-roy/fossfolio) in the list of static site generators in Python. 
NA

Add fossfolio: A static site generator in Python, with quick setup and intuitive codebase

---

src/site/generators/stenope.md

Add Stenope: a static website generator for Symfony apps & developers

---

src/site/headless-cms/payload-cms.md

Update Payload CMS details for going open-source

Payload CMS open-source update

---

src/site/generators/docsy.md

Hi @philhawksworth, I think that Docsy would a good addition to generators 😃

generators-google-docsy

---

src/site/generators/greenwood.md

Added [Greenwood](https://github.com/ProjectEvergreen/greenwood) to generators.

add Greenwood to generators

---

src/site/generators/simplified-saaze.md

Please add new generator to your list.
Thanks in advance.

New generator Simplified Saaze

---

src/site/headless-cms/wordpress.md

Figured WordPress should be on this list given it has a decent amount of usage in this space. I tested everything locally and it worked fine. Please let me know if there are any issues with this contribution. Thanks for curating this site.

Add WordPress to list of headless CMS

---

src/site/generators/iles.md

<p align="center">
<a href="https://iles-docs.netlify.app">
</a>
</p>

Add iles to the list of jamstack generators (close #719)

---

src/site/headless-cms/strapi.md

- Update Strapi page with 2 new features coming:
- Custom fields
- API Token v2

Update: Strapi page

---

netlify.toml
src/site/_includes/header.njk

I am archiving this project, so would like to remove links to it from the main Jamstack site.

Remove women of jamstack link

---

src/css/tailwind.css

Please do not merge this PR yet!

Add y-overflow to sticky nav on short viewports

---

src/site/headless-cms/plenti.md

Add Plenti as a headless CMS option.

---

src/site/generators/astro.md

Source: https://docs.astro.build/en/core-concepts/framework-components/
https://docs.astro.build/en/guides/markdown-content/

fixed templates for astro

---

src/site/generators/mdBook.md

fixed templates for mdbook

---

src/site/generators/fornax.md

Static site generator from Ionide and use f# programming language 
Signed-off-by: Muhammad Aviv Burhanudin <muhamadaviv14@gmail.com>

add fornax static site generator

---

src/site/headless-cms/webiny.md

- Update Twitter link
- Update feature list
- Delete gifs on page builder
- Add gif on headless CMS
- Add getting started links and resources
- Add quick start terminal command

feat(headless-cms): update info about webiny CMS

---

src/site/_includes/footer.njk

Add legal links to footer

---

src/site/generators/basildon.md

Adds a startertemplaterepo URL for the Basildon skeleton repository.

Add startertemplaterepo for Basildon skeleton

---

src/site/generators/next.md

Add twitter account for `@nextjs`

---

src/site/generators/hastie.md

Hastie switched from Go to Python

---

src/site/headless-cms/contentrain.md

Contentrain is a Git-based Headless CMS that was focused on developer and content editor experience which provide seamless integration with Jamstack web apps.

Added Contentrain Git Based Headless CMS

---

src/site/headless-cms/kentico-kontent.md

Fixes outdated description of the Kontent.ai platform

Update Kontent.ai description

---

src/site/generators/linkfree-gen.md

Add this super beginner-friendly SSG to the generators list

Add LinkFree Gen

---

src/site/generators/charge.md

Per the documentation, it supports MDX.

Add MDX template to Charge

---

src/site/headless-cms/graphapi.md

We are excited to be part of this list.

Added graphapi to the list of headless CMS

---

src/site/generators/haunt.md

Haunt is  written in Guile Programming language, Guile is an implementation of the [Scheme](http://schemers.org/) programming language.

fix language information

---

src/site/_includes/layouts/base.njk

This PR sets up the scripts necessary to connect google tag manager to this site.

Add google tag manager to base layout

---

src/site/generators/AspNetStatic.md

Hi. Please add AspNetStatic to your list of static site generators. Thank you.

Add AspNetStatic SSG info page.

---

src/site/headless-cms/contento.md

Hey!
This PR adds [Contento](http://contento.io/) to the headless CMS section.
Please do come back to us with any questions!
Thanks, Josh

Adds Contento CMS to headless CMS section

---

src/site/generators/abell.md

Hi there! I am the author of [abell](https://abelljs.org). 
Made some minor changes in the description and updated few things according to the new version of Abell.
Let me know if I missed something. Thanks!

feat(generators/abell): add updated information

---

src/site/headless-cms/graphweaver.md

Hi, 
Thanks for creating this great site!
I added the Graphweaver to the CMS section. 
[Graphweaver](https://graphweaver.com) is a GraphQL-based CMS with an Admin Panel to visually edit the connected data sources.
The project is 💯 open source and available here [https://github.com/exogee-technology/graphweaver](https://github.com/exogee-technology/graphweaver)

Added Graphweaver CMS

---

src/site/_data/announcementbar.json

hi hello yes it is me
https://www.youtube.com/watch?v=wwsMsolPrtw

Suggestion: Add Mike and Matt’s chat as an announcement bar

---

src/site/_data/announcementbar.json

https://thefutureofjamstack.org/

Update announcement banner with https://thefutureofjamstack.org/

---

src/site/headless-cms/builderio.md

Updating some of the content for Builder.io, including adding additional links to best represent Builder.

Update builder.io md

---

src/site/_data/glossary.yaml

Fix spelling error in glossary

---

src/site/generators/quarkus-roq.md

See: https://docs.quarkiverse.io/quarkus-roq/dev/index.html

Quarkus Roq static site generator

---

src/site/headless-cms/headless-hashnode.md

Adds Hashnode Headless as a CMS option

Added Hashnode Headless

---

src/site/generators/passage.md

Added Passage, a PHP based SSG.

Add passage to SSG list
