jamstack/jamstack.org

site/data/bestpractices.yaml, site/data/community.yaml, site/data/definitions.yaml
> Because JAMstack markup pre-built
The statement above feels like it's missing a verb. 
I also changed "pre-built" to be consistent with how prebuilt appears on `index.html`
=> Fix grammar and update JAMstack Dallas URL

site/layouts/pages/community.html
Active Ingredients is over. Need to add a layout for a list of multiple events, then update the data to match. For a quick fix in the meantime, I'm commenting out the events section in the layout.
=> Remove Active Ingredients

gulpfile.babel.js, site/config.yaml, site/content/best-practices.md, site/content/community.md, site/content/examples.md, site/content/pages/community.html, site/content/pages/examples.html, site/content/pages/resources.html, site/content/resources.md, site/layouts/_default/baseof.html, site/layouts/index.html, site/layouts/page/baseof.html, site/layouts/page/best-practices.html, site/layouts/page/community.html, site/layouts/page/examples.html, site/layouts/page/resources.html, site/layouts/partials/footer.html, site/layouts/partials/header.html, site/layouts/partials/html-head.html, site/layouts/partials/scripts.html
Made fixes and changes to the Hugo layout structure for the site.
- Created content as front matter markdown
- Created default layouts (baseof) for the page type
- Blocks (main, page-scripts) created for separation of html and scripts on a page
```html
{{ define "main" }}
{{ end }}
{{ define "page-scripts" }}
{{ end }}
```
- separated partials for layout re-use
- Fixed the quickfix for #87 to allow page scripts to follow linked scripts
- Used the jQuery `$(document).ready` method of loading an init function now that structure allows
**Considerations**
Could easily move this structure to a theme now, so might want to theme this layout, but not required.
=> Hugo site restructure for jamstack.org to be more hugo-centric

site/data/bestpractices.yaml, site/layouts/page/best-practices.html
Remove the arguably incorrect "headache" pointed out in #50, replacing with the less controversial "frustration."
Also noticed that the page content wasn't being processed as markdown, so `code` elements were rendered with backticks.
=> Replace "headache" with "frustration" and markdownify

site/data/examples.yaml
=> Proper capitalization of GitHub in examples.

site/data/community.yaml
The JAMstack Dallas meetup has disbanded and the meetup link 404s, so we should remove it for now.
Closes #150 
Signed-off-by: lesliecdubs <leslie@netlify.com>
=> Removing Dallas from Community page 😞

site/data/community.yaml
we don't know upon whose request we added philly to the list, and we have no information on who is doing anything there, so i am removing this meetup for now for inactivity.
=> remove philly meetup for inactivity

site/data/community.yaml
We received a request on gitter to edit the link for Jamstack Tokyo.
=> edit link for tokyo meetup

site/data/community.yaml
Fix the link to the paris meetup, which pointed to an individual event, not the main page. Remove link to Toulouse, as apparently they have deleted their meetup account and it went to a 404.
=> correct link for paris meetup, remove toulouse meetup link

site/layouts/page/baseof.html
When we introduced the JAMstack_conf banner, we only had it on the homepage, but kept the margins of the header, leaving a "hole".
This PR only makes sure the banner is visible in all pages.
=> Add JAMstack_conf banner to all pages

CONTRIBUTING.md
Instead of just referring to `jamstack.org`, it's a tad cleaner to refer to the actual name of the organisation and link to the referenced website as well.
=> Add JAMstack website link to CONTRIBUTING.md

src/site/_data/examples/smokeyfro.yaml
Replaces https://github.com/jamstack/jamstack.org/pull/335. ZEIT was rebranded to Vercel. Updates this to example to reflect the name change.
=> Rename ZEIT Now -> Vercel.

netlify.toml, plugins/keep-dot-cache-folder/index.js, plugins/keep-dot-cache-folder/manifest.yml, src/site/_data/github.js
1. Keep the `.cache` folder around to reduce API requests (once per day)
2. Fail the build if it hits an API error from GitHub for rate limiting (prevents production builds from deploying with missing data)
=> Fixes for GitHub API rate limits

src/site/what-is-jamstack.njk
Replaced `cirticial` with `critical`.
=> Fix word in what-is-jamstack

src/site/_data/glossary.yaml, src/site/what-is-jamstack.njk
Fix typos in the `Decoupling` glossary page.
Fixes #429, along with a couple other typos.
=> Various typo fixes

.eleventy.js, src/site/generators/tags.md
Markdown files were being pre-processed as liquid templates, this disables that feature. Also fixes the one markdown file that was using this feature 😅
=> Fixes #424

src/site/headless-cms/kentico-kontent.md
- fixed name of the file (-> to use the correct product name in the URL)
- fixed the SSG examples URL (leading to the official docs)
=> Updated URLs for Kentico Kontent

package.json
Also packaged in some other minor updates too. This was the beginning of an attempt to fix the dependabot issues at #467 but I don’t think they’re relevant any more since we deleted our package-lock.json and yarn lock files from the repo. Either way we can cement it with this explicit version upgrade.
Fixes #467
=> Update Eleventy to latest version

package.json, postcss.config.js, src/css/tailwind.css
Fixes #469, also upgrades all of the other deps too.
=> Upgrades major versions of TailwindCSS and PostCSS

src/site/_includes/layouts/base.njk
our google search console `jamstack.org` property needs re-verifying. 
including this new meta tag on production site will allow us to verify and manage domain in gsc.
=> updating google search console verification tag

src/site/_includes/layouts/base.njk
as per slack discussion, this initial tag removed (https://github.com/jamstack/jamstack.org/pull/499), may be tied to other google systems and services (zach recalls email alias setup needing this). adding this back in, just in case.
=> adding initial google-site-verification tag back in

src/js/lazyiframe.js, src/site/_includes/layouts/base.njk, src/site/index.njk
That `loading="lazy"` wasn’t cutting it.
Before:
After:
No JS experience (although irrelevant because you can’t play vimeo videos without JS anyway):
=> Lazy load the vimeo iframe for improved performance.

netlify.toml
The slack invite link expires every 30 days. Here's a fresh one.
=> fresh invite link

src/site/generators/saber.md
When you go the homepage of the site ([https://saber.land/](https://saber.land/)), and you click on the Github link to the repo, it redirects you to [saberland/saber](https://github.com/saberland/saber).
=> Add Saber repo (saberland/saber)

src/site/generators/log4brains.md
Repo: https://github.com/thomvaill/log4brains
> Log4brains is a docs-as-code knowledge base for your development and infrastructure projects. It enables you to write and manage Architecture Decision Records (ADR) right from your IDE, and to publish them automatically as a static website.
I released this new project a few days ago, and I hope you will find it interesting enough to add it to your awesome list!
I am also looking for beta testers and any feedback will be very welcome! 🙏
Thanks!
=> Add Log4brains to generators

package.json, src/css/tailwind.css, src/site/_data/community.yaml, src/site/_data/eleventyComputed.js, src/site/community.njk
Augments `community` global data from the YAML file to add `country` using some npm packages and eleventyComputed. I’m kinda proud of this approach! You *can* add the full `country` name in the community.yaml file if you want but it’s not necessary. Might be a useful escape hatch later for super-obscure locations. Uses the `<filter-container>` web component.
=> Adds filters by country to User Groups on Community page

src/site/generators/grazedocs.md
Changed GrazeDocs language, from CSharp to C#. So now it's listed with other C# written static site generators.
=> Fix GrazeDocs language

src/site/_data/glossary.yaml
Change "recieved" to "received" for glossary of _Pre-render/Pre-generate_.
=> Fix typo in glossary.yaml

src/site/_data/community.yaml
Adds a link to the Yerevan meetup group which is currently labeled on meetup as Jamstack Armenia
=> adding Yerevan as Armenia

src/site/_data/community.yaml
Updating the new Chicago meetup link to: https://www.meetup.com/b4974f5c-3d26-4bfb-8e24-6b670605fa9e/
=> Fis #587: Update Chicago meetup link

src/site/generators/tropical.md
G'day 🙂 I've rewritten my little site generator [Tropical](https://tropical.js.org/). This just updates the description to match.
Thanks!
=> Update Tropical description

netlify.toml, src/site/_data/glossary.yaml
Adds an entry to the glossary for DPR
`/glossary/dpr/`
This page and its generated summary card should be clear and free from typos(!)
closes: #552
=> Add DPR to glossary and adjust OG font size

src/site/_data/glossary.yaml
Conspicuously absent from the Glossary section!
Having a concise entry for the tern Jamstack to link to and share in tweets etc would be useful.
Visible here `/glossary/jamstack/`
And listed in`/glossary/` 
This definition will doubtless evolve and get refined over time.
=> A concise glossary entry for Jamstack itself

src/site/headless-cms/keystone.md
Last changes to this record (proposed by yours truly 🤦 ) had a forward slash in the frontmatter for Github repo. 
Merging this should get the stars back 🤩
=> Fixed Keystone Github Repo Ref

src/site/headless-cms/gathercontent.md
GatherContent is a content operations platform that supports Jamstack via its API offering.
=> Add GatherContent as headless CMS offering

src/site/_data/community.yaml
To close #638 and welcome the Barcelona meetup to the community.
Barcelona should now be visible on the `/community` page, and their future events should begin appearing in the touts of upcoming events.
=> adding Barcelona to the community

src/site/generators/next.md
The previous repository pointing to that isn't being maintained anymore. Visually there are no changes to either the website or the repository link. We just want to be sure that the project can still be deployed successfully for folks.
Repository link: https://github.com/netlify-templates/next-netlify-starter
Demo link: https://next-starter.netlify.app
=> Update Next.js template repo

src/site/index.njk
This PR:
- adds a CTA button to the Jamstack Conf callout on the landing page
- changes the containing anchor into a `<div>` so we don’t have nested links
- adds the location for the conf
- small style tweaks
=> Add cta to Jamstack Conf callout

netlify.toml
Prep for the 2022 Jamstack Conf page. Removing this to avoid an infinite redirect loop.
=> feat: remove conf redirect

netlify.toml
This request adds 200 redirects so that we can view the `jamstackconf.com` site at `jamstack.org/conf`
Noting that the following redirect rules were added in a [PR](https://github.com/netlify/jamstack_conf/pull/291) on the jamstack_conf repo. Once published, this will need to be tested to ensure it won't cause an infinite loop – I have a hunch it may be the case but I'm unsure of how we can test this without merging
```
[[redirects]]
from = "/"
to = "https://jamstack.org/conf/"
status = 301
force = true
[[redirects]]
from = "/*"
to = "https://jamstack.org/conf/:splat"
status = 301
force = true
```
=> Add jamstack conf site proxy redirect

src/site/_includes/survey/workflows.njk
In the device section, 'tablets' was typo'd as 'tables'
=> Fix typo in survey/workflows.njk

src/site/generators/astro.md
update displayname to the actual repo slug, however the old one still works as it redirects to the new one
=> Update repo slug

src/site/code-of-conduct.njk
Modified the first section of the code of conduct listing the 3 basic ground rules for improved readability. The updated version is more clear on the rules and the descriptions of each than the previous version.
=> Updated Code of Conduct Readability

src/site/_includes/header.njk, src/site/index.njk
This PR:
- adds a trailing slash to /conf/ link in navigation
- changes callout button link to /conf/
Closes https://github.com/jamstack/jamstack.org/issues/800
=> Update /conf/ link

src/site/index.njk
Elevates the Jamstack Conference promo section to the top of the jamstack.org home page.
=> Move up Jamstack Conf promo section

src/site/headless-cms/flycode.md
If I look at https://jamstack.org/headless-cms/, then I see 4 categories.
- Any CMS Type
- API Driven
- Git-based
- Git based
There's only one instance of `Git based` headless CMS types so I think this change should just fix this.
=> Fix typo: ~Git based~ -> Git-based

.eleventy.js, src/site/_data/meta.js, src/site/_includes/layouts/base.njk
- Adds new filter `absoluteUrl()`
- Sets `canonical` tag for jamstack.org sites
=> Set canonical tag link

src/site/headless-cms.njk
copy below the "Headless CMS" tag from its current state ("A List of Content Management Systems for Jamstack Sites") to "A list of headless content management systems for Jamstack sites." See ticket: https://github.com/netlify/marketing/issues/1911
=> Update current tag on Headless CMS page

src/site/generators/hugo.md
This PR changes the source repo for Hugo's "deploy to Netlify" button. The previous repo is now archived, which led to `fetch failed` errors after selecting the button.
=> update hugo repo

netlify.toml
Related to recent changes in https://github.com/jamstack/jamstack.org/pull/881
=> Add redirect from netlify-cms to decap-cms

README.md
The readme currently points people to broken paths in the `_data` folder and has people use yaml files instead of md frontmatter. I think this PR gives the correct instructions.
=> Update contribution instructions in README.md

src/site/generators/makestaticsite.md
Added an entry for MakeStaticSite, which is a 100% Bash solution, covered by AGPLv.3 to creating static snapshots with Wget with various post-processing and deployment options. 
Thank you for maintaining the list.
=> Added MakeStaticSite to the list of static site generators.

src/site/generators/docsy.md
else the generated link is `https://github.com/https://github.com/google/docsy` on https://jamstack.org/generators/docsy/
=> docsy: fix link

src/site/generators/docsy.md
On [Docsy’s listing](https://jamstack.org/generators/docsy/), the GitHub URL is currently `https://github.com/https://github.com/google/docsy`, and Twitter is `https://twitter.com/https://twitter.com/docsydocs/`.
=> Fix Twitter and GitHub links for Docsy

src/site/headless-cms/garchicms.md
Hi,
We have a headless CMS SaaS product named [Garchi CMS] (https://garchi.co.uk)
We would like to showcase it on jamstack.org/headless-cms site. 
In README.md it states to add a resource but I wasn't sure how to add it as a listing so I have added it in 
src/site/headless-cms
=> Garchi CMS added in site/headless-cms

src/site/generators/docpad.md
These repos moved to the docpad org
=> fix(docpad): some plugin links were outdated

src/site/generators/quarto.md
Created `quarto.md` in site/generators
=> Added Quarto as site generator

src/site/headless-cms/flycode.md
flycode.md is the only file which sets typeofcms to "Git based" instead of "Git-based".
This leads to the filter at https://jamstack.org/headless-cms/ to contain both versions even though they represent the same value
=> fix typeofcms filter value

src/site/generators/bestatic.md
Hi Jamstack Devs,
I am requesting inclusion of [Bestatic](https://www.bestaticpy.com/) static site generator on the jamstack.org. Thank you!
=> Add new static site generator Bestatic 

src/site/generators/haunt.md, src/site/generators/quarto.md, src/site/generators/stog.md
These three repo links were broken:
- Haunt
- Before: `https://github.com/https://github.com/quarto-dev/quarto-cli`
- After: `https://github.com/quarto-dev/quarto-cli`
- Quarto
- Before: `https://github.com/https://git.dthompson.us/haunt.git`
- After: *removed* (the repo on sourcehut can be found through the homepage link)
- Stog
- Before: `https://github.com/zoggy/stog` (non-existant)
- After: *removed* (the repo on a custom gitlab instance can be found through the homepage link)
=> Fix broken links to SSG repos

src/site/generators/sculpin.md
The Sculpin website notes its ability to use plain HTML & Markdown (https://sculpin.io/)
=> Sculpin: added HTML & Markdown

src/site/generators/hydephp.md
Adds HydePHP to the generators resource
=> Add HydePHP - Elegant and Powerful Static Site Generator

src/site/headless-cms/gitcms.md
Added GitCMS information in docs.
=> Added GitCMS - git based CMS info

netlify.toml, package.json, src/site/headless-cms/directus.md
Directus is licensed under the Business Source License as of now (April 2025).
Source: https://github.com/directus/directus/blob/main/license
=> Correct license for Directus that is no longer open source
